obj-$(CONFIG_SIKLU) = siklu_nand_boot.o \
	bank_management.o \
	common_boot.o \
	bank_management.o \
	common_config.o \
	common_mtd.o \
	common_fdt.o \
	siklu_led_control.o \
	siklu_load_device_configurations.o \
	siklu_device_config.o \
	siklu_spbs_command.o
